services:

  database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=dtrack
      - POSTGRES_DB=dtrack
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/

  dtrack-apiserver:
    image: dtrack/apiserver
    build:
      context: ./apiserver
      dockerfile: apiserver.dockerfile
    environment:
     - ALPINE_DATABASE_MODE=external
     - ALPINE_DATABASE_URL=jdbc:postgresql://database:5432/dtrack
     - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
     - ALPINE_DATABASE_USERNAME=dtrack
     - ALPINE_DATABASE_PASSWORD=changeme
     - ALPINE_DATABASE_POOL_ENABLED=true
     - ALPINE_DATABASE_POOL_MAX_SIZE=20
     - ALPINE_DATABASE_POOL_MIN_IDLE=10
     - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
     - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    volumes:
      - './data/apiserver:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: dtrack/frontend
    build:
      dockerfile: frontend.dockerfile
      context: ./frontend
    environment:
      - API_SERVICE_URL=http://dtrack-apiserver:8080
    ports:
      - "8080:8080"
    restart: unless-stopped
