version: '3.7'

services:
  dtrack-apiserver:
    image: dtrack/apiserver
    build:
      context: ./apiserver
      dockerfile: apiserver.dockerfile
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    volumes:
      - './data/apiserver:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: dtrack/frontend
    build:
      dockerfile: frontend.dockerfile
      context: ./frontend
    environment:
      - API_SERVICE_URL=http://dtrack-apiserver:8080
    ports:
      - "8080:8080"
    restart: unless-stopped
