name: Build

env:
  version: $(date +%s)

on:
  push:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f apiserver/apiserver.dockerfile --tag registry.ohrenpirat.de:5000/mwildt/dependency-track-apiserver:latest apiserver
    - name: Create Trivy sbom
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'registry.ohrenpirat.de:5000/mwildt/dependency-track-apiserver:latest'
        format: 'cyclonedx'
        exit-code: '1'
        ignore-unfixed: true
        output: dependency-track-apiserver.sbom.json
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-track-apiserver.sbom.json
        path: dependency-track-apiserver.sbom.json
    - name: Push Image
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo ${{ secrets.DOCKER_REPO_KEY }} | docker login -u github-build --password-stdin registry.ohrenpirat.de:5000
        docker push registry.ohrenpirat.de:5000/mwildt/dependency-track-apiserver:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f frontend/frontend.dockerfile --tag registry.ohrenpirat.de:5000/mwildt/dependency-track-frontend:latest frontend
    - name: Create Trivy sbom
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'registry.ohrenpirat.de:5000/mwildt/dependency-track-frontend:latest'
        format: 'cyclonedx'
        exit-code: '1'
        ignore-unfixed: true
        output: dependency-track-frontend.sbom.json
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-track-frontend.sbom.json
        path: dependency-track-frontend.sbom.json    
    - name: Push Image
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo ${{ secrets.DOCKER_REPO_KEY }} | docker login -u github-build --password-stdin registry.ohrenpirat.de:5000
        docker push registry.ohrenpirat.de:5000/mwildt/dependency-track-frontend:latest
